#!/bin/bash
####################################################################################
###
### Harbi miner for ton.ninja
### os.dog integration: shatll(@osdog)
###
####################################################################################

#   example
#
#	{
#		"miner":"lolminer",
#		"algo":"nexapow",
#		"online":"1707474764",
#		"total_hr":"71842910",
#		"total_share":"1",
#		"total_badshare":"0",
#		"ver":"1.82a",
#		"hr":[11580000,27740000,0,0,2990000,0,22650000,6880000],
#		"share":[0,1,0,0,0,0,0,0],
#		"badshare":[0,0,0,0,0,0,0,0],
#		"invshare":[0,0,0,0,0,0,0,0],
#		"busid":["03","05","06","07","09","0b","0c","0d"],
#		"coin":"NEXA"
#		"temp":[31,28,29,29,31,29,30,30],     #  unnecessary field if 'busid' is provided
#		"temp2":[38,35,35,35,37,34,37,37],    #  unnecessary field if 'busid' is provided
#		"temp3":[0,0,0,0,0,0,0,0],            #  unnecessary field if 'busid' is provided
#		"fan":[45,45,44,45,44,44,45,46],      #  unnecessary field if 'busid' is provided
#	}


baseDir=`dirname $0`


LOG="/dog/log/harbi.log"

algo="harbihash"
miner="pHarbi-miner"

ver='0.7.1'
data=$(
		jq -n \
    --arg algo "$algo" \
    --arg miner "$miner" \
		'{
			$miner,
			$algo
		}'
)
minername="pHarbi-miner"
online_raw=`ps -C $minername -o etimes= | awk '{print $1}' | tac | tail -n 1`
if [[ ! -z $online_raw ]]; then
  online=$(date --date "-$online_raw sec" +%s) #absolute time
  data=`jq ". += {\"online\": $online}" <<< "$data"`
fi

linesToSearch=100
logPart=`tail -n $linesToSearch $LOG`

platform0_busids=`cat /run/dog/gpuStats | jq '[[.gpu[] | select(.brand == "N")] | .[].b]'`
#platform1_busids=`cat /run/dog/gpuStats | jq '[[.gpu[] | select(.brand == "A")] | .[].b]'` # amd is not working atm
gpuCount=`echo $platform0_busids | jq '. | length'`

busid_json=[]
hr_json=[]
totalHr=0
for (( i=0; i < ${gpuCount}; i++ )); do
  gpuHrStr=`echo "$logPart" | grep "GPU #${i}" | tail -n 1`
  hr=`echo $gpuHrStr | sed -e 's/.*hashrate = //; s/ H\/s//'`
  busid=`echo $platform0_busids | jq -r ".[$i]"`
  busid_json=`jq ". += [\"$busid\"]" <<< "$busid_json"`
  hr_json=`jq ". += [$hr]" <<< "$hr_json"`
  totalHr=`echo "$totalHr + $hr" | bc`
done

if [[ ! -z $busid_json ]]; then
  data=`jq ". += {\"busid\": $busid_json}" <<< "$data"`
fi

if [[ ! -z $hr_json ]]; then
  data=`jq ". += {\"hr\": $hr_json}" <<< "$data"`
  data=`jq ". += {\"total_hr\": $totalHr}" <<< "$data"`
fi

#   finally return json data
echo "$data" | jq -c
#
#local stats_raw=`cat $LOG | grep -a "hashrate" | tail -n 1 | tr -d '\0'`
#				local maxDelay=120
#				local time_now=`date +%s`
#				local datetime_rep=`echo $stats_raw | awk '{print $1}' | awk -F[ '{print $2}'`
#				local time_rep=`date -d $datetime_rep +%s`
#
#				diffTime=`echo $((time_now-time_rep)) | tr -d '-'`
#
#				if [[ "$diffTime" -lt "$maxDelay" ]]; then
#					local miner_online_raw=`ps -C $miner -o etimes= | awk '{print $1}'`
#					[[ ! -z $miner_online_raw ]] && local miner_online=$(date --date "-$miner_online_raw sec" +%s) #absolute time
#
#					local multiplier
#					[[ $stats_raw == *"Ghash"* ]] && multiplier=1000000000 || multiplier=1000000
#					local miner_total_hr_raw=`echo "$stats_raw" | awk '{print $7}'`
#					local miner_total_hr=`echo "scale=0; $miner_total_hr_raw * $multiplier / 1" | bc -l`
#
#					local shares_raw=`cat $LOG | grep -a "Shares: Accepted:" | tail -n 1 | tr -d '\0'`
#					local miner_total_share=`echo "$shares_raw" | awk '{print $6}'`
#
#					local gpuList=`cat $GPUSTATS_FILE | jq '.gpu'`
#					local gpuCount=`echo $gpuList | jq -r '. | length'`
#
#					local miner_busid_json=`echo $gpuList | jq '[.[].b]'`
#
#					local hash_arr=()
#
#					for(( i=0; i < gpuCount; i++ )); do
#						local gpu_raw=`cat $LOG | grep -a "Device #"$i | tail -n 1 `
#						local hr_raw=`echo $gpu_raw | awk '{print $(NF-1)}'`
#						[[ $gpu_raw == *"Ghash"* ]] && multiplier=1000000000 || multiplier=1000000
#						local hr=`echo "scale=0; $hr_raw * $multiplier / 1" | bc -l`
#
#						hash_arr+=($hr)
#
#					done
#
#					local miner_hr_json=`printf '%s\n' "${hash_arr[@]}" | jq -cs '.'`
#				fi
