#!/bin/bash
####################################################################################
###
### aleo-f2pool
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
MINER_DIR=files
CONFIG_FILE=$MINER_DIR/config.txt
LOG="/dog/log/aleo-f2pool-miner.log"

#	custom package body
####################################################################################

args=
#	default values for miner
[[ $POOL ]] && args+=" -u $POOL"
[[ $TEMPLATE ]] && args+=" -w $TEMPLATE"

if [[ "$ADDITION" != *"-d "* ]]; then
  nvidiaGpuCount=`gpu-detect NVIDIA`
  [[ $nvidiaGpuCount -eq 0 ]] && echo -e "${RED}> No NVIDIA GPU detected${WHITE}" && exit 1
  let maxGpu=$nvidiaGpuCount-1

  args+=" -d 0"
  for ((i=1; i<$nvidiaGpuCount; i++)); do
    args+=",$i"
  done
fi

args="$args $ADDITION"

$LINE
echo -e "${GREEN}> Starting custom miner${WHITE}"
batch="./aleominer $args"
#	unbuffer is needed to keep colors with tee
unbuffer $batch 2>&1 | tee --append $LOG
