#!/bin/bash
####################################################################################
###
### GPU miner
### os.dog integration: @osdog
###
####################################################################################

#	example
#
#	{
#		"miner":"lolminer",
#		"algo":"nexapow",
#		"online":"1707474764",
#		"total_hr":"71842910",
#		"total_share":"1",
#		"total_badshare":"0",
#		"ver":"1.82a",
#		"temp":[31,28,29,29,31,29,30,30],
#		"temp2":[38,35,35,35,37,34,37,37],
#		"temp3":[0,0,0,0,0,0,0,0],
#		"fan":[45,45,44,45,44,44,45,46],
#		"hr":[11580000,27740000,0,0,2990000,0,22650000,6880000],
#		"share":[0,1,0,0,0,0,0,0],
#		"badshare":[0,0,0,0,0,0,0,0],
#		"invshare":[0,0,0,0,0,0,0,0],
#		"busid":["03","05","06","07","09","0b","0c","0d"],
#		"coin":"NEXA"
#	}

algo="TONHash"
miner="GpuMiner"

LOG_FILE="/dog/log/gpu-miner.log"
GPU_STATS="/run/dog/gpuStats"
gpuCount=$(jq '.gpu | length' < "$GPU_STATS")

busid_json='[]'
declare -a hr_data=( )

# Инициализируем массив hr_data нулями
for (( i=0; i < gpuCount; i++ )); do
    hr_data+=(0)
done

readarray -t speed_lines < <(tail -n 170 "$LOG_FILE" | grep "instant speed" | tail -n "$gpuCount")

for (( i=0; i < gpuCount; i++ )); do
    busid=$(jq -r ".gpu[$i].b" < "$GPU_STATS")
    busid_json=$(jq ". += [\"$busid\"]" <<< "$busid_json")

    if [[ -n "${speed_lines[$i]}" ]]; then
        instant_speed=$(echo "${speed_lines[$i]}" | grep -oP 'instant speed: \K[0-9.]+(?= Mhash/s)')
        # Обновляем hr_data только если instant_speed больше 0
        if (( $(echo "$instant_speed > 0" | bc -l) )); then
            hr_data[$i]=$instant_speed
        fi
    fi
done

# Трансформируем hr_data в JSON для jq
hr_json=$(printf '%s\n' "${hr_data[@]}" | jq -R . | jq -s .)

# Вычисляем общий хешрейт
totalHr=0
for hr in "${hr_data[@]}"; do
    totalHr=$(echo "$totalHr + $hr" | bc)
done

lastLine=$(tail -n 1 "$LOG_FILE" | sed 's/\x1b\[[0-9;]*m//g')
total_share=$(echo "$lastLine" | awk '{print $7}')

data=$(
    jq -n \
        --arg algo "$algo" \
        --arg miner "$miner" \
        --argjson busid "$busid_json" \
        --argjson hr "$hr_json" \
        --argjson total_share "$total_share" \
    '{
        miner: $miner,
        algo: $algo,
        total_hr: "'"$totalHr"'",
        busid: $busid,
        hr: $hr,
        total_share: $total_share
    }'
)

echo "$data" | jq -c
