#!/bin/bash
####################################################################################
###
### xnt-drpool
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`
. ./utils.sh

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
LOG="/dog/log/xnt-drpool.log"

#	custom package body
####################################################################################

echo "> additional args: $ADDITION"
REMAINING_ARGS=""
parse_args "$ADDITION" devices
remainingAddition=$REMAINING_ARGS
echo "> remaining args: $remainingAddition"

# Determine GPU list
if [[ $devices ]]; then
  gpu_list=$devices
else
  # Get NVIDIA GPU count from gpuStats
  gpu_count=$(cat /run/dog/gpuStats | jq '[.gpu[] | select(.brand == "N")] | length')
  if [[ $gpu_count -gt 0 ]]; then
    # Generate list: 0,1,2,3...
    gpu_list=$(seq -s',' 0 $((gpu_count - 1)))
  else
    gpu_list="0"
  fi
fi

echo "> using GPUs: $gpu_list"

$LINE
echo -e "${GREEN}> Starting custom miner${WHITE}"
batch="./xntprover -p $POOL -w $TEMPLATE -g $gpu_list $remainingAddition"
echo "$batch"
#	unbuffer is needed to keep colors with tee
unbuffer $batch 2>&1 | tee --append $LOG

