#!/bin/bash

####################################################################################
###
### xmrig-nvidia
### os.dog integration: @osdog
###
####################################################################################

#	example
#
#	{
#		"miner":"qubitcoin-miner",
#		"algo":"qhash",
#		"online":"1707474764",
#		"total_hr":"71842910",
#		"total_share":"1",
#		"total_badshare":"0",
#		"ver":"0.68.1",
#		"temp":[31,28,29,29,31,29,30,30],
#		"temp2":[38,35,35,35,37,34,37,37],
#		"temp3":[0,0,0,0,0,0,0,0],
#		"fan":[45,45,44,45,44,44,45,46],
#		"hr":[11580000,27740000,0,0,2990000,0,22650000,6880000],
#		"share":[0,1,0,0,0,0,0,0],
#		"badshare":[0,0,0,0,0,0,0,0],
#		"invshare":[0,0,0,0,0,0,0,0],
#		"busid":["01","04","05","07","08","09","0a","0b"],
#		"coin":"QBC"
#	}

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"

dirname=$(dirname "$0")
[[ -f "$dirname/$CFG_FILENAME" ]] && . $dirname/$CFG_FILENAME

# GPU count will be determined from API response
gpuCount=0

busid_json=`cat /run/dog/gpuStats | jq '[[.gpu[] | select(.brand == "N")] | .[].b]'`
declare -a hr_data=( )
declare -a acc_data=( )
declare -a rej_data=( )

API_TIMEOUT=2

miner_online_raw=
miner_ver=
miner=
algo=

# Get summary data from JSON API
json_data=$(curl -s --connect-timeout $API_TIMEOUT localhost:$API_PORT/summary 2>/dev/null)
if [[ -n $json_data && $json_data != *"curl: ("* ]]; then
    # Extract basic miner info
    miner_online_raw=$(echo "$json_data" | jq -r '.connection.uptime // empty')
    miner_ver=$(echo "$json_data" | jq -r '.version // empty')
    algo=$(echo "$json_data" | jq -r '.algo // empty')

    ua=$(echo "$json_data" | jq -r '.ua // "XMRig-NVIDIA/unknown"')
    miner=$(echo "$ua" | cut -d'/' -f1)

    totalShares=$(echo "$json_data" | jq -r '.results.shares_total')
    totalAcc=$(echo "$json_data" | jq -r '.results.shares_good')
    totalRej=$((totalShares - totalAcc))

    # Get hashers array
    hashers=$(echo "$json_data" | jq -r '.hashrate.threads // []')
#    echo "$hashers" | jq '.'
    gpuCount=$(echo "$hashers" | jq 'length')
    
    if [[ $gpuCount -gt 0 ]]; then
        # Initialize arrays
        hr_data=()

        # Process each hasher
        for (( i=0; i < gpuCount; i++ )); do
            # Extract hashrate (first element of hashrate array)
            hr=$(echo "$hashers" | jq -r ".[$i][0] // 0")
            hr_data+=($hr)
        done
    fi
fi

# Handle case when no GPU data is available
if (( gpuCount == 0 )); then
    hr_json='[]'
else
    hr_json=$(printf '%s\n' "${hr_data[@]}" | jq -R . | jq -s .)
fi

# calculate total_hr
totalHr=0
for val in "${hr_data[@]}"; do
    totalHr=$(echo "$totalHr + $val" | bc)
done

data=$(
    jq -n \
        --arg algo "$algo" \
        --arg miner "$miner" \
        --arg ver "$miner_ver" \
        --argjson busid "$busid_json" \
        --argjson hr "$hr_json" \
    '{
        $miner,
        $algo,
        $ver,
        total_hr: "'"$totalHr"'",
        total_share: "'"$totalAcc"'",
        total_badshare: "'"$totalRej"'",
        busid: $busid,
        hr: $hr
    }'
)

if [[ ! -z $miner_online_raw ]]; then
  online=$(date --date "-$miner_online_raw sec" +%s)
  data=`jq ". += {\"online\": $online}" <<< "$data"`
fi

echo "$data" | jq -c