#!/bin/bash
####################################################################################
###
### martis miner
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
MINER_DIR=files
CONFIG_FILE=$MINER_DIR/config.txt
LOG="/dog/log/martis-miner.log"

#	custom package body
####################################################################################

#	this miner need many dependencies, so install script is placed in individual file
#	if the miner is builded or you don`t need to install ton of dependecies, you can
#	remove this string or install something right here
./install.sh

if [[ "$ADDITION" == *"-gpu-count="* ]]; then
  gpuCount=`echo "$ADDITION" | sed -e 's/.*-gpu-count=//; s/ .*//'`
  [[ $gpuCount == "all" ]] && unset gpuCount # to fit next if block
fi

if [[ ! $gpuCount ]]; then
  GPU_STATS="/run/dog/gpuStats"
  gpuCount=$(jq '.gpu | length' < "$GPU_STATS")
fi

screen-kill node
for (( i=0; i < gpuCount; i++ )); do
  dir="/home/user/martiscoin/node$i"
  mkdir -p $dir
  cp msc.conf "$dir/Martiscoin/msc.conf"

  apiPort="5552$i"
  #  args="-apiuri=http://0.0.0.0 -apiport=4242$i -mineaddress=$WALLET -server=0 -mine=1 -useopencl=1 -opencldevice=$i"
  #  args+=" -connect=$HOME_NODE -addnode=$HOME_NODE -iprangefiltering=0"
  args="-datadir=$dir -mineaddress=$WALLET -iprangefiltering=0 -server=0 -mine=1 -useopencl=1 -opencldevice=$i -port=1933$i"
  [[ "$ADDITION" != *"-apiport="* ]] && args+=" -apiport=$apiPort"
  [[ $i -gt 0 ]] && args+=" -connect=127.0.0.1:19330" # all nodes should connect to first one

  batch="dotnet files/Martiscoin.Node.dll $args $ADDITION"
  echo -e "${BROWN}> GPU[$i] batch:${WHITE}\n$batch\n"
  screen -dmS node$i $batch
done

trap ctrl_c INT

function ctrl_c() {
  echo "Ctrl + C happened"
  screen-kill node
}

tail -f /dev/null
