#!/bin/bash
####################################################################################
###
### martis miner
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
MINER_DIR=files
CONFIG_FILE=$MINER_DIR/config.txt
LOG="/dog/log/martis-miner.log"

#	custom package body
####################################################################################

#	this miner need many dependencies, so install script is placed in individual file
#	if the miner is builded or you don`t need to install ton of dependecies, you can
#	remove this string or install something right here
./install.sh

HOME_NODE="192.168.2.9:19333"

GPU_STATS="/run/dog/gpuStats"
gpuCount=$(jq '.gpu | length' < "$GPU_STATS")
for (( i=0; i < gpuCount; i++ )); do
  dir="/home/user/martiscoin/node$i"
  mkdir -p $dir
  cp msc.conf $dir
  #  args="-apiuri=http://0.0.0.0 -apiport=4242$i -mineaddress=$WALLET -server=0 -mine=1 -useopencl=1 -opencldevice=$i"
  #  args+=" -connect=$HOME_NODE -addnode=$HOME_NODE -iprangefiltering=0"
  args="-datadir=$dir -mineaddress=$WALLET -server=0 -mine=1 -useopencl=1 -opencldevice=$i -apiport=5552$i"
  args+=" -addnode=$HOME_NODE -whitelist=$HOME_NODE -iprangefiltering=0"
  batch="dotnet files/Martiscoin.Node.dll $args $ADDITION"
  echo -e "GPU[$i] starting mining with next batch:\n$batch"
  screen-kill node$i
  screen -dmS node$i $batch
done

trap ctrl_c INT

function ctrl_c() {
  echo "Ctrl + C happened"
  screen -ls
  for (( i=0; i < gpuCount; i++ )); do
      screen-kill node$i
  done
  screen -ls
}

tail -f /dev/null
