#!/bin/bash
####################################################################################
###
### NOCK goldenminer
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors

cd `dirname $0`
. ./utils.sh

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
CONFIG_FILE=config.env
LOG="/dog/log/goldenminer.log"
#	custom package body
####################################################################################

echo "> additional args: $ADDITION"
REMAINING_ARGS=""
parse_args "$ADDITION" name threadsPerCard devices
remainingAddition=$REMAINING_ARGS
echo "> remaining args: $remainingAddition"

[[ ! $name ]] && name=$(hostname)
if [[ ! $threadsPerCard ]]; then
  nproc_count=$(nproc)
  if [[ $devices ]]; then
    # Count devices from comma-separated list
    IFS=',' read -ra device_array <<< "$devices"
    gpu_count=${#device_array[@]}
  else
    gpu_count=$(gpu-detect NVIDIA)
  fi
  if [[ $gpu_count -gt 0 ]]; then
    threadsPerCard=$((nproc_count / gpu_count))
    [[ $threadsPerCard -lt 1 ]] && threadsPerCard=1
  else
    threadsPerCard=1
  fi
fi

$LINE
batch="./golden-miner-pool-prover --pubkey $WALLET --name $name --threads-per-card=$threadsPerCard $remainingAddition"

echo -e "${GREEN}> Starting custom miner:${WHITE}"
if [[ $devices ]]; then
  echo "CUDA_VISIBLE_DEVICES=$devices $batch"
  export CUDA_VISIBLE_DEVICES=$devices
  unbuffer $batch 2>&1 | tee $LOG
else
  echo "$batch"
  unbuffer $batch 2>&1 | tee $LOG
fi