#!/bin/bash
####################################################################################
###
### UPOWAI miner for ton.ninja
### os.dog integration: shatll(@osdog)
###
####################################################################################

#   example
#
#	{
#		"miner":"lolminer",
#		"algo":"nexapow",
#		"online":"1707474764",
#		"total_hr":"71842910",
#		"total_share":"1",
#		"total_badshare":"0",
#		"ver":"1.82a",
#		"hr":[11580000,27740000,0,0,2990000,0,22650000,6880000],
#		"share":[0,1,0,0,0,0,0,0],
#		"badshare":[0,0,0,0,0,0,0,0],
#		"invshare":[0,0,0,0,0,0,0,0],
#		"busid":["03","05","06","07","09","0b","0c","0d"],
#		"coin":"NEXA"
#		"temp":[31,28,29,29,31,29,30,30],     #  unnecessary field if 'busid' is provided
#		"temp2":[38,35,35,35,37,34,37,37],    #  unnecessary field if 'busid' is provided
#		"temp3":[0,0,0,0,0,0,0,0],            #  unnecessary field if 'busid' is provided
#		"fan":[45,45,44,45,44,44,45,46],      #  unnecessary field if 'busid' is provided
#	}


baseDir=`dirname $0`


LOG="/dog/log/upowai.log"

algo="sha256"
miner="upow-gpu"

ver='0.1'
data=$(
		jq -n \
    --arg algo "$algo" \
    --arg miner "$miner" \
		'{
			$miner,
			$algo
		}'
)
minername="cuda"
online_raw=`ps -C $minername -o etimes= | awk '{print $1}' | tac | tail -n 1`
if [[ ! -z $online_raw ]]; then
  online=$(date --date "-$online_raw sec" +%s) #absolute time
  data=`jq ". += {\"online\": $online}" <<< "$data"`
fi


platform0_busids=`cat /run/dog/gpuStats | jq '[[.gpu[] | select(.brand == "N")] | .[].b]'`
#platform1_busids=`cat /run/dog/gpuStats | jq '[[.gpu[] | select(.brand == "A")] | .[].b]'` # amd is not working atm
gpuCount=`echo $platform0_busids | jq '. | length'`

linesToSearch=`echo "$gpuCount * 4" | bc`
logPart=`tail -n $linesToSearch $LOG`

busid_json=[]
hr_json=[]
totalHr=0
for (( i=0; i < ${gpuCount}; i++ )); do
  gpuHrStr=`echo "$logPart" | grep "^${i}. " | tail -n 1`
  hrRaw=`echo $gpuHrStr | sed -e 's/.*: //; s/ GH\/s//'`
  hr=`echo "$hrRaw * 1000000000" | bc -l`
  busid=`echo $platform0_busids | jq -r ".[$i]"`
  busid_json=`jq ". += [\"$busid\"]" <<< "$busid_json"`
  hr_json=`jq ". += [$hr]" <<< "$hr_json"`
  totalHr=`echo "$totalHr + $hr" | bc`
done

if [[ ! -z $busid_json ]]; then
  data=`jq ". += {\"busid\": $busid_json}" <<< "$data"`
fi

if [[ ! -z $hr_json ]]; then
  data=`jq ". += {\"hr\": $hr_json}" <<< "$data"`
  data=`jq ". += {\"total_hr\": $totalHr}" <<< "$data"`
fi

#   finally return json data
echo "$data" | jq -c
