services:
  miner:
    build: .
    container_name: qubitcoin-miner
    restart: unless-stopped
    environment:
      GPU_COUNT: ${GPU_COUNT}
    ports:
      - "127.0.0.1:44440-44447:44440-44447"
    volumes:
      - /dog/log:/app/log
