#!/bin/bash
####################################################################################
###
### 8infinity miner
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
CONFIG_FILE=config.env
LOG="/dog/log/8infinity-miner.log"

#	custom package body
####################################################################################

#	this miner need many dependencies, so install script is placed in individual file
#	if the miner is builded or you don`t need to install ton of dependecies, you can
#	remove this string or install something right here
./install-docker.sh

echo -e "${BROWN}> pulling docker image${WHITE}"
docker pull otonashilabs/infinity-miner:latest
echo -e "${GREEN}> pulling docker image completed${WHITE}"

# parse args
parse_args() {
    # Цвета
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    WHITE='\033[0m'

    local args="$1"
    shift
    local keys=("$@")

    read -ra tokens <<< "$args"

    for key in "${keys[@]}"; do
        local value=""
        for i in "${!tokens[@]}"; do
            if [[ "${tokens[$i]}" == "--$key" ]]; then
                value="${tokens[$((i+1))]}"
                break
            fi
        done

        local var_name="${key//-/_}"
        if [ -n "$value" ]; then
            printf -v "$var_name" '%s' "$value"
            #echo -e "${GREEN}> $var_name = ${!var_name}${WHITE}"
            echo -e "${GREEN}> args parsed: $var_name${WHITE}"
        else
            printf -v "$var_name" '%s' ""
            echo -e "${RED}> args parsed: no value for $var_name${WHITE}"
        fi

        export "$var_name"
    done
}
parse_args "$ADDITION" master-address master-pkey infinity_rpc infinity_ws
[ -z "$infinity_rpc" ] && infinity_rpc="https://rpc.blaze.soniclabs.com"
[ -z "$infinity_ws" ] && infinity_ws="wss://rpc.blaze.soniclabs.com"

# create config
conf="REWARDS_RECIPIENT_ADDRESS=$WALLET"
conf+="\nMASTER_ADDRESS=$master_address"
conf+="\nMASTER_PKEY=$master_pkey"

conf+="\nINFINITY_RPC=$infinity_rpc"
conf+="\nINFINITY_WS=$infinity_ws"

echo -e "$conf" > $CONFIG_FILE

$LINE
echo -e "${GREEN}> Starting custom miner${WHITE}"

# exec it needed to change main process from shell to unbuffer + docker
#	unbuffer is needed to keep colors with tee
exec unbuffer docker run --gpus all --rm -it --name $MINERNAME -v ./$CONFIG_FILE:/app/.env otonashilabs/infinity-miner:latest python3 mine_infinity.py 2>&1 | tee --append "$LOG"
