#!/bin/bash
####################################################################################
###
### 8infinity miner
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
CONFIG_FILE=config.env
LOG="/dog/log/8infinity-miner.log"
GIT_REPO=https://github.com/shatll-s/8infinity-miner
GIT_DIR=files
#	custom package body
####################################################################################

# install part
apt-get install -yqq python3 python3-pip git
git clone $GIT_REPO.git $GIT_DIR
pip3 install -r $GIT_DIR/requirements.txt


# parse args
parse_args() {
    local args="$1"
    shift
    local keys=("$@")

    read -ra tokens <<< "$args"

    for key in "${keys[@]}"; do
        local value=""
        for i in "${!tokens[@]}"; do
            if [[ "${tokens[$i]}" == "--$key" ]]; then
                value="${tokens[$((i+1))]}"
                break
            fi
        done

        local var_name="${key//-/_}"
        if [ -n "$value" ]; then
            printf -v "$var_name" '%s' "$value"
            #echo -e "${GREEN}> $var_name = ${!var_name}${WHITE}"
            echo -e "${GREEN}> args parsed: $var_name${WHITE}"
        else
            printf -v "$var_name" '%s' ""
            echo -e "${RED}> args parsed: no value for $var_name${WHITE}"
        fi

        export "$var_name"
    done
}
parse_args "$ADDITION" master-address master-pkey infinity_rpc infinity_ws
[ -z "$infinity_rpc" ] && infinity_rpc="https://rpc.blaze.soniclabs.com"
[ -z "$infinity_ws" ] && infinity_ws="wss://rpc.blaze.soniclabs.com"

$LINE
echo -e "${GREEN}> Starting custom miner:${WHITE}"

INFINITY_REWARDS_RECIPIENT_ADDRESS=$WALLET
INFINITY_MINER_PRIVATE_KEY=$master_pkey
INFINITY_RPC=$infinity_rpc
INFINITY_WS=$infinity_ws python3 src/main.py

batch="python3 $GIT_DIR/src/main.py"
echo -e "$batch"

#	unbuffer is needed to keep colors with tee
unbuffer $batch 2>&1 | tee --append $LOG
