#!/bin/bash
####################################################################################
###
### neptune
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
LOG="/dog/log/neptune.log"

#	custom package body
####################################################################################

##	this miner need many dependencies, so install script is placed in individual file
##	if the miner is builded or you don`t need to install ton of dependecies, you can
##	remove this string or install something right here
#./install.sh

args=$ADDITION

$LINE
echo -e "${GREEN}> Starting custom miner${WHITE}"
echo "$batch"
#./dr_neptune_prover --pool stratum+tcp://neptune.drpool.io:30127 -w drpoolaccount.xxx
batch="./dr_neptune_prover -p $POOL -w $TEMPLATE $args"
#	unbuffer is needed to keep colors with tee
unbuffer $batch 2>&1 | tee --append $LOG

