#!/bin/bash
####################################################################################
###
### qubitcoin miner
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
CONFIG_FILE=config.env
LOG="/dog/log/qubitcoin-miner.log"
#	custom package body
####################################################################################

# install section
./install.sh

# install section end

# parse args
parse_args() {
    local args="$1"
    shift
    local keys=("$@")

    read -ra tokens <<< "$args"

    for key in "${keys[@]}"; do
        local value=""
        for i in "${!tokens[@]}"; do
            if [[ "${tokens[$i]}" == "--$key" ]]; then
                value="${tokens[$((i+1))]}"
                break
            fi
        done

        local var_name="${key//-/_}"
        if [ -n "$value" ]; then
            printf -v "$var_name" '%s' "$value"
            #echo -e "${GREEN}> $var_name = ${!var_name}${WHITE}"
            echo -e "${GREEN}> args parsed: $var_name${WHITE}"
        else
            printf -v "$var_name" '%s' ""
            echo -e "${RED}> args parsed: no value for $var_name${WHITE}"
        fi

        export "$var_name"
    done
}
parse_args "$ADDITION" reserved_cores
[ -z "$reserved_cores" ] && reserved_cores=2

$LINE
echo -e "${GREEN}> Starting custom miner:${WHITE}"

nvidiaCount=$(gpu-detect nvidia)
MY_PID=$$
total_cores=$(nproc)
usable_cores=$((total_cores - reserved_cores))
base_threads=$((usable_cores / nvidiaCount))
extra_threads=$((usable_cores % nvidiaCount))

for ((i = 0; i < nvidiaCount; i++)); do
  threads=$base_threads
  if (( i < extra_threads )); then
    threads=$((threads + 1))
  fi
  echo "> GPU $i → -t $threads"
  screenName="qubitcoin-miner$i"
  apiPort="4444$i"
  log="/dog/log/qubitcoin-miner$i.log"
  batch="CUDA_VISIBLE_DEVICES=$i ./qubitcoin-miner --algo qhash --url $POOL --coinbase-addr $WALLET --userpass $PASS $ADDITION -t $threads --api-bind $apiPort"

  fullBatch=$(cat <<EOF
(
  ( while kill -0 $MY_PID 2>/dev/null; do sleep 1; done
    echo "GPU $i: parent died, shutting down miner..."
    kill \$\$ ) &

  while true; do $batch 2>&1 | tee -a $log; done
)
EOF
)

  echo "$batch"

  screen-kill $screenName
  screen -dmS "$screenName" bash -c "$fullBatch"
done

# for infinity
tail -f /dev/null
