#!/bin/bash
####################################################################################
###
### zkwork
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
MINER_DIR=files
CONFIG_FILE=$MINER_DIR/config.txt
MINER_URL='https://github.com/6block/zkwork_aleo_gpu_worker/releases/download/v0.2.1/aleo_prover-v0.2.1.tar.gz'
EXEC_FILE='aleo_prover'
EXEC_FILE_SUM='9f0f15a0834f7654eed44c9147eec757'
LOG="/dog/log/zkwork.log"

#	custom package body
####################################################################################
tmpDir="/tmp/tmp_zkwork"

needToDownload=1
if [[ -f $EXEC_FILE ]]; then
  md5sum=`md5sum $EXEC_FILE | awk '{print $1}'`
  if [[ $md5sum == $EXEC_FILE_SUM ]]; then
    needToDownload=0
  else
    echo -e "${RED}> Miner file is downloaded, but corrupted${WHITE}"
  fi
fi

if [[ $needToDownload == 1 ]]; then
  echo -e "${BROWN}> Need to download ${CYAN}$EXEC_FILE${WHITE}"
  rm -rf $tmpDir
  mkdir -p $tmpDir
  wget --no-check-certificate $MINER_URL -O $tmpDir/archive.tar.gz

  tar -xf $tmpDir/archive.tar.gz -C $tmpDir
  mv $tmpDir/aleo_prover/aleo_prover aleo_prover
  chmod 777 aleo_prover
  echo -e "${GREEN}> Miner file is downloaded${WHITE}"
else
  echo -e "${GREEN}> Miner file is already downloaded${WHITE}"
fi

md5sum=`md5sum $EXEC_FILE | awk '{print $1}'`
[[ $md5sum != $EXEC_FILE_SUM ]] && echo -e "${RED}> ERROR: ${CYAN}$EXEC_FILE${WHITE} is corrupted${WHITE}" && exit 1

args=
#	default values for miner
[[ $POOL ]] && args+=" --pool $POOL"
[[ $TEMPLATE ]] && args+=" --address $TEMPLATE"

if [[ "$ADDITION" != *"--custom_name "* ]]; then
  alias=`cat /etc/hostname`
  args+=" --custom_name $alias"
fi

args="$args $ADDITION"
batch="./$EXEC_FILE $args"

$LINE

echo -e "${GREEN}> Starting custom miner with next settings:${WHITE}"
echo -e "$batch"

#	unbuffer is needed to keep colors with tee
unbuffer $batch 2>&1 | tee --append $LOG
