#!/bin/bash
####################################################################################
###
### zkwork
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
MINER_DIR=files
CONFIG_FILE=$MINER_DIR/config.txt
EXEC_FILE='aleo_prover'
LOG="/dog/log/zkwork.log"

#	custom package body
####################################################################################

args=
#	default values for miner
[[ $POOL ]] && args+=" --pool $POOL"
[[ $TEMPLATE ]] && args+=" --address $TEMPLATE"

if [[ "$ADDITION" != *"--custom_name "* ]]; then
  alias=`cat /etc/hostname`
  args+=" --custom_name $alias"
fi

args="$args $ADDITION"
batch="./$EXEC_FILE $args"

$LINE

echo -e "${GREEN}> Starting custom miner with next settings:${WHITE}"
echo -e "$batch"

#	unbuffer is needed to keep colors with tee
unbuffer $batch 2>&1 | tee --append $LOG
