#!/bin/bash
####################################################################################
###
### ninjarig feeless miner
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

#	global variables, don`t change it
####################################################################################
#	The file contains the following variables:
#	MINERNAME API_PORT CUSTOM_URL POOL PASS WALLET TEMPLATE COIN ADDITION
CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

#	custom package variables
####################################################################################
CONFIG_FILE=config.env
LOG="/dog/log/ninjarig-feeless.log"
#	custom package body
####################################################################################
. ./utils.sh

echo "> additional args: $ADDITION"
REMAINING_ARGS=""
parse_args "$ADDITION" a algo
remainingAddition=$REMAINING_ARGS
echo "> remaining args: $remainingAddition"
ALGO=
if [[ $a ]]; then
  ALGO=$a
elif [[ $algo ]]; then
  ALGO=$algo
else
  ALGO="hashlayer"
fi
#[[ ! $diff ]] && diff=26
#[[ ! $region ]] && region=eu

$LINE
echo -e "${GREEN}> Starting custom miner${WHITE}"

free_port $API_PORT

batch="./dogminer -a $ALGO -o $POOL -u $TEMPLATE --api-port $API_PORT $remainingAddition"
$batch 2>&1 --log-file $LOG